spring:
  application:
    name: event-manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event_manager_db
    username: ravil
    password: ravil
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    url: /openapi.yaml
